### ISSUE TITLE
Training script for minimal DETR

### ISSUE THREAD

**Issue by bkj** [facebookresearch/detr#320] opened 2021-01-21 02:46 UTC
Hi --

The [detr_demo](https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_demo.ipynb) notebook shows a simplified version of the model that gets to ~ 40 AP on `COCO val5k`.

Are you able to share the training code / information about training parameters for that model?  Or is the training routine identical to the training of the full-scale DETR models included in this repo?

Thanks!

**Comment by alcinos** [comment] 2021-01-27 16:53
Duplicate of #300 (someone provided a training script there) and #63
Note that the demo model doesn't support batching on the same node and thus is quite hard to train (requires multi-nodes), but if you disable batching and remove the nested tensors, you should be able to use the training code for the normal DETR.

However, I want to stress that it is really intended as a demo to understand the general data flow in the model and not something anyone should use in anything serious beyond tinkering. The "official" model is not that much more complicated, I encourage you to dig into it once you've understood how the minimal version works.

I believe I have answered your question, and as such I'm closing this. Feel free to reach out if you have further concerns.

**Closed by alcinos** 2021-01-27 16:53 UTC
