### ISSUE TITLE
Mixed Precision Training with Pytorch AMP

### ISSUE THREAD

**Issue by jackkwok** [facebookresearch/detr#167] opened 2020-07-29 23:56 UTC
I would like to use the latest Mix Precision Training feature from Pytorch 1.6.  My code crashes at 

`loss_dict = criterion(outputs, targets)`

The crash has to do with type mismatch between types **c10::Half** and **float**:

Traceback (most recent call last):
  File "main.py", line 257, in <module>
    main(args)
  File "main.py", line 207, in main
    args.clip_max_norm)
  File "/home/ext_jack_gmail_com/detr/engine.py", line 37, in train_one_epoch
    loss_dict = criterion(outputs, targets)
  File "/home/ext_jack_gmail_com/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ext_jack_gmail_com/detr/models/detr.py", line 225, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/home/ext_jack_gmail_com/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ext_jack_gmail_com/.local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/ext_jack_gmail_com/detr/models/matcher.py", line 74, in forward
    cost_giou = -generalized_box_iou(box_cxcywh_to_xyxy(out_bbox), box_cxcywh_to_xyxy(tgt_bbox))
  File "/home/ext_jack_gmail_com/detr/util/box_ops.py", line 53, in generalized_box_iou
    iou, union = box_iou(boxes1, boxes2)
  File "/home/ext_jack_gmail_com/detr/util/box_ops.py", line 28, in box_iou
    lt = torch.max(boxes1[:, None, :2], boxes2[:, :2])  # [N,M,2]
RuntimeError: Expected object of scalar type c10::Half but got scalar type float for argument 'other'

The code with my minor changes: https://gist.github.com/jackkwok/5d48034f5129f8dfc4a9b362b40b54c4

Any idea how I can debug this?

I am developing on pytorch nightly build: torch==1.7.0.dev20200727

**Comment by fmassa** [comment] 2020-07-30 16:56
Hi,

This is a duplicate of https://github.com/facebookresearch/detr/issues/127

I think what @szagoruyko did was to make the `criterion` outside of the `amp` context.

**Closed by fmassa** 2020-07-30 16:56 UTC

**Comment by jackkwok** [comment] 2020-07-30 17:07
I tried moving ceriterion outside of amp autocast context but I got the same **"cdist_cuda" not implemented for 'Half'** error @szagoruyko ran into:

Traceback (most recent call last):
  File "main.py", line 257, in <module>
    main(args)
  File "main.py", line 207, in main
    args.clip_max_norm)
  File "/home/ext_jack_gmail_com/detr/engine.py", line 37, in train_one_epoch
    loss_dict = criterion(outputs, targets)
  File "/home/ext_jack_gmail_com/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ext_jack_gmail_com/detr/models/detr.py", line 225, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/home/ext_jack_gmail_com/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ext_jack_gmail_com/.local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/ext_jack_gmail_com/detr/models/matcher.py", line 71, in forward
    cost_bbox = torch.cdist(out_bbox, tgt_bbox, p=1)
  File "/home/ext_jack_gmail_com/.local/lib/python3.7/site-packages/torch/functional.py", line 979, in cdist
    return _VF.cdist(x1, x2, p, None)
RuntimeError: "cdist_cuda" not implemented for 'Half'

**Comment by fmassa** [comment] 2020-07-31 12:48
I haven't tried it myself, but I would make a cast in the input of the criterion so that all tensors are float.

**Comment by pjuangph** [comment] 2021-04-04 03:35
I think I managed to get mixed precision to work. I am currently training this. I modified this function the following 

```python
def train_one_epoch(model: torch.nn.Module, criterion: torch.nn.Module,
                    data_loader: Iterable, optimizer: torch.optim.Optimizer,
                    device: torch.device, epoch: int, max_norm: float = 0):
    model.train()
    criterion.train()
    metric_logger = utils.MetricLogger(delimiter="  ")
    metric_logger.add_meter('lr', utils.SmoothedValue(window_size=1, fmt='{value:.6f}'))
    metric_logger.add_meter('class_error', utils.SmoothedValue(window_size=1, fmt='{value:.2f}'))
    header = 'Epoch: [{}]'.format(epoch)
    print_freq = 100
    scaler = torch.cuda.amp.GradScaler()
    i = 0
    for samples, targets in metric_logger.log_every(data_loader, print_freq, header):        
        samples = samples.to(device)        
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]
        with torch.cuda.amp.autocast():
            outputs = model(samples)            
            loss_dict = criterion(outputs, targets)
            weight_dict = criterion.weight_dict
            losses = sum(loss_dict[k] * weight_dict[k] for k in loss_dict.keys() if k in weight_dict)

            # reduce losses over all GPUs for logging purposes
            loss_dict_reduced = utils.reduce_dict(loss_dict)
            loss_dict_reduced_unscaled = {f'{k}_unscaled': v
                                        for k, v in loss_dict_reduced.items()}
            loss_dict_reduced_scaled = {k: v * weight_dict[k]
                                        for k, v in loss_dict_reduced.items() if k in weight_dict}
            losses_reduced_scaled = sum(loss_dict_reduced_scaled.values())

            loss_value = losses_reduced_scaled.item()

        if not math.isfinite(loss_value):
            print("Loss is {}, stopping training".format(loss_value))
            print(loss_dict_reduced)
            sys.exit(1)

        
        scaler.scale(losses).backward()
        if ((i+1) % print_freq == 0) or i== len(data_loader):             # Wait for several backward steps
            # Unscales gradients and calls
            # or skips optimizer.step()
            scaler.step(optimizer)
            # Updates the scale for next iteration
            scaler.update()
            model.zero_grad()                           # Reset gradients tensors
            optimizer.zero_grad()
        
        i+=1

        if max_norm > 0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm)
        

        metric_logger.update(loss=loss_value, **loss_dict_reduced_scaled, **loss_dict_reduced_unscaled)
        metric_logger.update(class_error=loss_dict_reduced['class_error'])
        metric_logger.update(lr=optimizer.param_groups[0]["lr"])
    # gather the stats from all processes
    metric_logger.synchronize_between_processes()
    print("Averaged stats:", metric_logger)
    return {k: meter.global_avg for k, meter in metric_logger.meters.items()}
```

**Comment by JiHaoqina** [comment] 2021-07-09 14:59
@pjuangph Hi, can your pasted code work now? I'm trying to use apex.amp in detr, too
