### ISSUE TITLE
Bug in official Colab implementeation

### ISSUE THREAD

**Issue by Mastemace** [facebookresearch/detr#168] opened 2020-07-30 08:52 UTC
Hi, when you use the official [implementation on Colab](https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_demo.ipynb) and predict image **http://images.cocodataset.org/val2017/000000527220.jpg**, the detect throws following error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-11d682adb58b> in <module>()
      2 im = Image.open(requests.get(url, stream=True).raw)
      3 
----> 4 scores, boxes = detect(im, detr, transform)

2 frames
<ipython-input-2-f9392da44538> in forward(self, inputs)
     59             self.col_embed[:W].unsqueeze(0).repeat(H, 1, 1),
     60             self.row_embed[:H].unsqueeze(1).repeat(1, W, 1),
---> 61         ], dim=-1).flatten(0, 1).unsqueeze(1)
     62 
     63         # propagate through the transformer

RuntimeError: Sizes of tensors must match except in dimension 2. Got 50 and 74 in dimension 1
```

Other images (I tried 200 others) are working. But there will be more (such as 000000329614.jpg) where the bug appears as well. Can you please fix it?

**Comment by fmassa** [comment] 2020-07-30 16:47
Hi,

This is a duplicate of https://github.com/facebookresearch/detr/issues/37

This works fine if you clamp the image to a max size of 1333.

I'm closing this as a duplicate, but let us know if you have further questions

**Comment by fmassa** [comment] 2020-07-30 16:48
Also, we would happily accept a PR that clamps the max size of the image to be 1333

**Closed by fmassa** 2020-07-30 16:47 UTC

**Comment by Mastemace** [comment] 2020-07-30 16:57
Thank you for your answer. In other words, it is impossible to replicate your results on COCO with the Colab notebook? I know here is written it is just minimal implementation, but still, I thought it is a minimal implementation able to confirm the numbers.
