### ISSUE TITLE
Help on Training a Small custom data set

### ISSUE THREAD

**Issue by Prabakaran-Chandran** [facebookresearch/detr#14] opened 2020-05-28 13:51 UTC
Hi Team, 
I am.working on a custom dataset , which has 7 classes and I have 1500 images , I wanna train on DeTR, help me out how should I train the model 

Thanks in advance

**Comment by alcinos** [comment] 2020-05-28 13:55
Closing this as it is a duplicate of #9. Please look at the discussion there and see if it answers your question.

**Closed by alcinos** 2020-05-28 13:55 UTC
Labels: duplicate
