### ISSUE TITLE
Is it possible to optimize encoder inference efficiency

### ISSUE THREAD

**Issue by twangnh** [facebookresearch/detr#128] opened 2020-07-02 07:10 UTC
Hi! thanks for sharing the wonderful work! I observe when using the larger output resolution for backbone, e.g., the DC5 model in the paper, the encoder is going to take a lot of time, I'm wondering if we can optimize the matmul/bmm operation to improve the speed, or current low-level implementation is already fast enough that there is not much room of improvement? I'm not familiar with low-level things, can someone give some advice?

**Comment by fmassa** [comment] 2020-07-02 11:53
Hi,

Most of the time spent on the decoder is in `matmul`, which have very efficient implementations in C++ / CUDA.
The issue is that the matrices that we use are huge, which makes it use a lot of memory and end up being very slow.

In order to make the encoder faster, approaches such as Linformer https://github.com/facebookresearch/detr/issues/80 could be used, but it's a research topic and would require experimentation to validate that it works as well.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions.

**Closed by fmassa** 2020-07-02 11:53 UTC
