### ISSUE TITLE
NMS?

### ISSUE THREAD

**Issue by pfeatherstone** [facebookresearch/detr#72] opened 2020-06-09 08:46 UTC
Do you need to apply NMS after having filtered out the detections with poor score and those with the nothing class?

**Comment by fmassa** [comment] 2020-06-09 09:04
Hi,

This is a duplicate of https://github.com/facebookresearch/detr/issues/34, and related to https://github.com/facebookresearch/detr/issues/10

As we mention in the paper (and in Figure 4), DETR doesn't require NMS. You can see that our post-processor only perform softmax and box coordinates conversion.

https://github.com/facebookresearch/detr/blob/be9d447ea3208e91069510643f75dadb7e9d163d/models/detr.py#L274-L282

I'm closing this issue as a duplicate, but please let us know if you have further questions.

**Closed by fmassa** 2020-06-09 09:04 UTC

**Comment by pfeatherstone** [comment] 2020-06-09 11:37
So all you have to do is, out of the 100 detections, remove the ones with the 'nothing' class?

**Comment by fmassa** [comment] 2020-06-09 12:57
@pfeatherstone it depends on what you want to do.

You have two choices:
- use our postprocessor, which always returns a valid object class for all the 100 proposals, even if "no-object" is the class with highest score (note the `:-1` in `prob[..., :-1].max(-1) `. This improves recall on COCO detection, as it will also have classes with low probabilities. This implies that you need to set a threshold for visualizations.
- you can take the "no-object"  while computing the max scores, and discard those with "no-object" classes.
