### ISSUE TITLE
How to generate pt file?

### ISSUE THREAD

**Issue by KenWebber** [facebookresearch/detr#308] opened 2020-12-22 13:38 UTC
Hello all!
I try to convert my model from .pth to .pt, so that I can test my detr model in pytorch android application.I have tried so many ways I had seen online, however I can't find the correct one, .all results can't work in the android application. 
Anyone can help me please? I don't know how to work the next step.
Thank you.

**Comment by zhiqwang** [comment] 2020-12-28 03:00
Hi @KenWebber , I think that you can refer to the discussion here https://github.com/facebookresearch/detr/issues/309#issuecomment-751345149

**Comment by alcinos** [comment] 2021-01-14 00:28
Closing as a likely duplicate of #309

**Closed by alcinos** 2021-01-14 00:28 UTC
